# Generated by Django 5.2.7 on 2025-11-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка админки',
                'verbose_name_plural': 'Настройки админки',
                'db_table': 'admin_settings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(db_column='id_cat', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id_company', models.AutoField(db_column='id_company', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Компания',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id_dish', models.AutoField(db_column='id_blu', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_category', models.ForeignKey(db_column='fk_id_cat', on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.category')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='Ordr',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(db_column='deliverydate')),
                ('delivery_time', models.TimeField(blank=True, db_column='deliverytime', null=True)),
                ('delivery_address', models.TextField(db_column='deliveryaddress')),
                ('status', models.CharField(default='новый', max_length=20)),
                ('id_company', models.ForeignKey(db_column='fk_id_company', on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'verbose_name': 'Заказ',
                'db_table': 'ordr',
            },
        ),
        migrations.CreateModel(
            name='OrdrItem',
            fields=[
                ('id_ordritem', models.AutoField(db_column='id_item', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('id_dish', models.ForeignKey(db_column='fk_id_blu', on_delete=django.db.models.deletion.CASCADE, to='core.dish')),
                ('id_ordr', models.ForeignKey(db_column='fk_id_order', on_delete=django.db.models.deletion.CASCADE, to='core.ordr')),
            ],
            options={
                'verbose_name': 'Позиции заказов',
                'db_table': 'ordritem',
            },
        ),
    ]
